[package]
name = "async_chat"
version = "0.1.0"
authors = ["Damien Stanton <damien.stanton@gmail.com>"]
edition = "2018"

[[bin]]
name = "async_chat"
path = "src/bin/main.rs"

[dependencies]
async-std = { version = "1", features = ["unstable"] }
futures = "0.3"
structopt = "0.3"